-- USE auto_matching;
INSERT IGNORE INTO ng_ages
VALUES
  ('40');
INSERT IGNORE INTO ng_ages
VALUES
  ('41');
INSERT IGNORE INTO ng_ages
VALUES
  ('42');
INSERT IGNORE INTO ng_ages
VALUES
  ('43');
INSERT IGNORE INTO ng_ages
VALUES
  ('44');
INSERT IGNORE INTO ng_ages
VALUES
  ('45');
INSERT IGNORE INTO ng_ages
VALUES
  ('46');
INSERT IGNORE INTO ng_ages
VALUES
  ('47');
INSERT IGNORE INTO ng_ages
VALUES
  ('48');
INSERT IGNORE INTO ng_ages
VALUES
  ('49');
INSERT IGNORE INTO ng_ages
VALUES
  ('50');
INSERT IGNORE INTO ng_ages
VALUES
  ('51');
INSERT IGNORE INTO ng_ages
VALUES
  ('52');
INSERT IGNORE INTO ng_ages
VALUES
  ('53');
INSERT IGNORE INTO ng_ages
VALUES
  ('55');
INSERT IGNORE INTO ng_ages
VALUES
  ('55');
INSERT IGNORE INTO ng_ages
VALUES
  ('56');
INSERT IGNORE INTO ng_ages
VALUES
  ('57');
INSERT IGNORE INTO ng_ages
VALUES
  ('58');
INSERT IGNORE INTO ng_ages
VALUES
  ('59');
INSERT IGNORE INTO ng_ages
VALUES
  ('60');
INSERT IGNORE INTO ng_ages
VALUES
  ('61');
INSERT IGNORE INTO ng_ages
VALUES
  ('62');
INSERT IGNORE INTO ng_ages
VALUES
  ('63');
INSERT IGNORE INTO ng_ages
VALUES
  ('66');
INSERT IGNORE INTO ng_ages
VALUES
  ('65');
INSERT IGNORE INTO ng_ages
VALUES
  ('66');
INSERT IGNORE INTO ng_ages
VALUES
  ('67');
INSERT IGNORE INTO ng_ages
VALUES
  ('68');
INSERT IGNORE INTO ng_ages
VALUES
  ('69');
INSERT IGNORE INTO ng_ages
VALUES
  ('70');